-- public.branch_priorities_current — branch Today "Today's Priorities" (API)
--
-- Canonical definition (from public.today_priorities via JSONB + priorities_engine):
--   rebuild-priorities-family-from-today-priorities-jsonb.sql
--
-- That script creates priorities_engine → priorities_ranked → branch_priorities_current
-- (top 2 per branch) and drops legacy today_priorities_ranked / today_priorities_view.
--
-- Do not use the old definition against today_priorities_ranked after the rebuild.
