-- public.company_priorities_current is created by:
--   rebuild-priorities-family-from-today-priorities-jsonb.sql
--
-- That script builds the view from public.today_priorities via to_jsonb (flexible keys)
-- and drops legacy today_priorities_company_view. Do not recreate an alias to
-- today_priorities_company_view here after running the rebuild.
--
-- Legacy (only if you still maintain today_priorities_company_view and have no
-- company_priorities_current yet):
--   CREATE OR REPLACE VIEW public.company_priorities_current AS
--   SELECT * FROM public.today_priorities_company_view;
--   GRANT SELECT ON public.company_priorities_current TO anon, authenticated;
