-- What’s Working: canonical definition in rebuild-alerts-enriched-engine.sql (STEP 6d).
--
-- Exposed object: public.whats_working_today only.
-- Legacy aliases whats_working_today__candidate / whats_working_today_v_next were removed from the
-- rebuild script; drop any stragglers with drop-whats-working-alias-views.sql.
--
-- Contract: title = headline, description = grey line; columns:
--   organization_id, branch_id, branch_name, metric_date, title, description, sort_score
--
-- Deploy: run rebuild STEP 6d (or full rebuild-alerts-enriched-engine.sql).
-- Verify: SELECT branch_id, metric_date, title FROM public.whats_working_today ORDER BY branch_id;
