-- Company Today page reads these objects (create in Supabase to match your summary pipeline).
--
-- daily_metrics (read-only UNION view): if /rest/v1/daily_metrics returns 502, run
-- recreate-daily-metrics-view.sql (branch_id as uuid; splits accommodation_daily_metrics + fnb_daily_metrics).
-- If daily_metrics is still a legacy TABLE, rename it before recreating the view (see script header).
-- Expected columns are flexible; the web app maps common aliases (see company-today-data-service.ts).
--
-- **Run `add-branch-performance-signal-and-business-status.sql`** — app reads `branch_business_status` + `branch_performance_signal`
-- Optional: run `drop-today-summary-clean-safe-view.sql` after migrating off the legacy view.
--
-- **Recommended:** run `add-branch-performance-signal-and-business-status.sql` (in order: drop views →
-- branch_performance_signal → branch_business_status). Requires accommodation_profitability_signal,
-- fnb_profitability_signal, today_summary_clean (via branch_business_status), branches.
--
-- Unified alerts pipeline (recommended): run the **entire** rebuild-alerts-enriched-engine.sql script
-- (not bare view names). Uses branch_business_status (backed by today_summary_clean + signals).
--   alerts_enriched → alerts_today → branch_alerts_today (alias), alerts_critical, alerts_top3_revenue_leaks, alerts_fix_this_first
-- Branch Today UI: add-branch-alerts-today.sql or rebuild (fixes /rest/v1/branch_alerts_today 404)
-- Verify: SELECT * FROM alerts_today LIMIT 5;
--
-- 1) branch_business_status (see add-branch-performance-signal-and-business-status.sql for full definition)
--    branch_id, organization_id, branch_name, branch_type,
--    health_score, occupancy_pct, revenue_thb, adr, rooms_sold, rooms_total, revpar, customers, avg_ticket,
--    profitability_trend (accommodation), margin_trend + avg_daily_cost (F&B),
--    metric_date, days_since_update, freshness_status
--
-- 2) alerts_today
--    branch_id, impact_estimate_thb (or estimated_revenue_impact), …
--
-- 3) alerts_critical
--    branch_id, branch_name?, alert_title | alert_name, cause | alert_message,
--    impact_estimate_thb, action | recommendation
--
-- 4) alerts_top3_revenue_leaks
--    branch_id, branch_name?, alert_type, impact_estimate_thb, cause, recommended_action (optional rank)
--
-- 4b) alerts_fix_this_first (Company Today — Fix This First; add-alerts-fix-this-first-view.sql or rebuild-alerts-enriched-engine.sql)
--    branch_id, organization_id, branch_name, alert_type, severity, impact_estimate_thb, cause, recommended_action, priority_score
--
-- 4c) today_priorities / today_priorities_clean — add-today-priorities-view.sql or rebuild-alerts-enriched-engine.sql
--     400 on API: run fix-today-priorities-clean-400.sql (ensures organization_id + sort_score columns).
--
-- 4d) whats_working_today — add-whats-working-today-view.sql or rebuild-alerts-enriched-engine.sql
--     Positive signals from today_summary_clean; highlight_text for company Today page.
--
-- 4e) opportunities_today — add-opportunities-today-view.sql or rebuild-alerts-enriched-engine.sql
--     opportunity_text from alerts_enriched (alert_category = opportunity); requires alerts pipeline.
--    clean: branch_id, organization_id, branch_name, alert_type, action_text, short_title,
--           impact_estimate_thb, impact_label (at risk|opportunity), reason_short, sort_score
--
-- 5) company_daily_summary — run add-company-daily-summary.sql (creates table + RLS; fixes /rest/v1/company_daily_summary 404)
--    organization_id, summary_text, updated_at, created_at, summary_date, id
--
-- 6) company_data_confidence — add-company-data-confidence-view.sql
--    GET /rest/v1/company_data_confidence?select=*&organization_id=eq.{uuid}
--    organization_id, data_days, max_days (30), confidence_level (Low|Medium|High)
--
-- 7) company_trends_summary — add-company-trends-summary-view.sql
--    GET /rest/v1/company_trends_summary?select=*&organization_id=eq.{uuid}
--    is_ready, revenue_pct_vs_prior_week, drivers_text, occupancy_pct, customers_total,
--    mix_rooms_pct, mix_fnb_pct, trend_line
--
-- GRANT SELECT ON … TO authenticated;
