-- =============================================================================
-- DEPRECATED for Company Today business trends
-- =============================================================================
-- Use: rebuild-business-trends-today-from-today-summary.sql
--
-- A prior variant sourced business_trends_today from daily_metrics and deleted
-- orphans against daily_metrics. That could remove rows that still existed in
-- public.today_summary (e.g. F&B on a date present only in today_summary join),
-- breaking parity with the Today pipeline.
-- =============================================================================
